# Generated by Django 3.0.4 on 2022-07-22 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
    ]
